# Generated by Django 6.0.7 on 2026-08-06 10:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='total_monthly_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='monthly_due',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='balance_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='portion',
            name='price_modifier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subsidypolicy',
            name='daily_cap',
            field=models.DecimalField(decimal_places=2, help_text="Plafond quotidien maximal de la subvention en devise (= 'daily_quota' de l'algo)", max_digits=10),
        ),
        migrations.AlterField(
            model_name='subsidypolicy',
            name='monthly_allowance_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Administrateur Plateforme'), ('COMPANY_ADMIN', 'RH / Admin Entreprise'), ('RESTAURANT_ADMIN', 'Gérant Restaurant'), ('RESTAURANT_SERVER', 'Serveur Restaurant'), ('EMPLOYEE', 'Employé')], default='EMPLOYEE', max_length=20),
        ),
        migrations.CreateModel(
            name='RestaurantServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='served_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.restaurantserver'),
        ),
    ]
