# Generated by Django 6.0.7 on 2026-08-06 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_total_monthly_bill_restaurant_monthly_due_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='administered_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='leave_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
