# Generated by Django 6.0.7 on 2026-08-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_company_admins_employeeprofile_leave_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='portion',
        ),
        migrations.DeleteModel(
            name='Portion',
        ),
    ]
