# Generated by Django 6.0.7 on 2026-08-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_orderitem_portion_delete_portion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidypolicy',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='subsidypolicy',
            name='daily_cap',
            field=models.DecimalField(decimal_places=2, help_text='Montant de la subvention individuelle par employé et par jour (en FCFA)', max_digits=10),
        ),
    ]
